
let quote = "Then say \"ok\"."

let movie =
"""
Hello!
I'm Nusaiba
How are you?
"""

print(movie)

let nameLength = movie.count
print(nameLength)

print(movie.uppercased())
print(movie.hasPrefix("Help"))
print(movie.hasSuffix("!"))

let score = 10
let reallyBig = 1_000_000

print(reallyBig)

let lScore = reallyBig - 2
let halvedScore = reallyBig / 2

var counter = 10
counter += 5
print(counter)

counter *= 2
print(counter)

let number = 120

print(number.isMultiple(of: 3))
print(120.isMultiple(of: 5))

let a = Double(2)
let fNumber = a + 0.1
print(fNumber)

var myName = "Nusaiba Rahman"
myName = "Charli"
print(myName)
myName = 007 // will Error - no type reassignment




